config/routes.rb
Rails.application.routes.draw do
  get 'landing_page/index'

  resources :orders

  root 'landing_page#index' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  #validates :title, presence: true, length: {minimum: 5}
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all 
  end

  def new
    @order = Order.new
  end

  def create
    #render plain: params[:order].inspect
    @order = Order.new(order_params)
    if @order.save
      redirect_to @order
    else
      render 'new'
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  private
    def order_params
      params.require(:order).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/landing_page/index.html.erb
<H1>Hello Phoria</h1>
<%= link_to 'Shop', controller: 'orders' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phoria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with model: @order, local: true do |form| %>
 
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@order.errors.count, "error") %> prohibited
        this order from being saved:
      </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/orders/index.html.erb
<h1>Listing Orders</h1>

<%= link_to 'New order', new_order_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.title %></td>
      <td><%= order.text %></td>
      <td><%= link_to 'Show', order_path(order) %></td>
    </tr>
  <% end %>
</table>

app/views/orders/new.html.erb
<h1>New Article</h1>
<%= render 'form'%>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @order.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @order.text %>
</p>

<%= link_to 'Back', orders_path %>